// ─────────────────────────────────────────────────────────
// GENESIS CHAMBER V4 — MARKDOWN EXPORT
// Clean markdown export with title, sources, images
// ─────────────────────────────────────────────────────────

function stripHTML(text) {
  if (!text) return '';
  return text.replace(/<[^>]*>/g, '');
}

function resolveUrl(img) {
  if (typeof img === 'string') return img;
  return img.url || img.data || '';
}

function downloadBlob(content, filename, type) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Export content as a clean markdown file.
 * @param {string} content — markdown/text content
 * @param {Object} opts
 * @param {string} opts.title
 * @param {string} opts.modelName
 * @param {string} opts.date
 * @param {Array} opts.sources — [{url, title}]
 * @param {Array} opts.images — [string | {url, alt}]
 * @param {string} opts.filename — base filename (no extension)
 */
export function exportToMD(content, { title, modelName, date, sources, images, filename } = {}) {
  const lines = [];

  // Header
  if (title) {
    lines.push(`# ${title}`);
    const meta = [modelName, date].filter(Boolean).join(' · ');
    if (meta) lines.push(`*${meta}*`);
    lines.push('');
  }

  // Body — strip HTML but keep markdown syntax
  const body = stripHTML(content || '');
  lines.push(body);
  lines.push('');

  // Sources
  if (sources && sources.length > 0) {
    lines.push('## Sources');
    lines.push('');
    sources.forEach((s) => {
      const label = (s.title && s.title !== s.url) ? s.title : s.url;
      lines.push(`- [${label}](${s.url})`);
    });
    lines.push('');
  }

  // Images
  if (images && images.length > 0) {
    lines.push('## Images');
    lines.push('');
    images.forEach((img, i) => {
      const url = resolveUrl(img);
      const alt = (typeof img === 'object' && img.alt) || `Image ${i + 1}`;
      lines.push(`![${alt}](${url})`);
    });
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('*Generated by Genesis Chamber LLM Council*');

  const md = lines.join('\n');
  const baseName = (filename || title || 'export')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 80);

  downloadBlob(md, `${baseName}.md`, 'text/markdown');
}
